# Generated by Django 2.2.10 on 2021-10-26 09:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='release',
            field=models.DateField(default=datetime.date.today, verbose_name='发行时间'),
        ),
    ]
